export const TAGS = [
  "Academic",
  "A Cappella",
  "Advising",
  "Advocacy",
  "Arts",
  "Business",
  "Charity",
  "Civic engagement",
  "Club Sports",
  "Comedy",
  "Community Service",
  "Competitive",
  "Consulting",
  "Cultural",
  "Dance",
  "Design",
  "Engineering",
  "Entrepreneurship",
  "Environmental",
  "First Generation Low Income (FGLI)",
  "Food",
  "Global affairs",
  "Greek Life",
  "Health",
  "Instructional",
  "Journalism",
  "Law",
  "LGBTQ+",
  "Media",
  "Medicine",
  "Mentorship",
  "Music",
  "Outdoors",
  "Peer Education",
  "Performing Arts",
  "Politics",
  "Pre-professional",
  "Programming",
  "Publication",
  "Public speaking",
  "Recreation",
  "Religious/Spiritual",
  "Science",
  "Social",
  "Social Science",
  "Special Interest",
  "Student Governance",
  "Technology",
  "Theatre",
  "Travel",
  "Umbrella Organization",
  "Writing",
  "Youth",
] as const;

export const AFFILIATIONS = [
  "ESAC",
  "SAC",
  "SCC",
  "Wharton Council",
  "PAC",
] as const;

export type Tag = (typeof TAGS)[number];
export type Affiliation = (typeof AFFILIATIONS)[number];